### ISSUE TITLE
The right click menu should be closed after a click in the bookmark pop-up

### ISSUE THREAD

**Issue by oleedd** [rpkamp/chrome-minimal-bookmarks-tree#102]
If the right click menu was opened accidentally - not possible to close it and need to reload the bookmark pop-up. Even scrolling won't help.
So just need to add a left click listener for `document`.

**Comment by oleedd** [comment]
It still doesn't close after scrolling.

**Comment by rpkamp** [comment]
Chrome itself also doesn't close a context menu when you scroll. I explicitly tried when solving this issue. 

Not a bug. Won't fix.

**Comment by oleedd** [comment]
> Chrome itself also doesn't close a context menu when you scroll.

It isn't for me. Chrome close the right click menu at starting scrolling.

**Comment by oleedd** [comment]
> Chrome itself also doesn't close a context menu when you scroll.

It isn't for me. Chrome close the right click menu at starting scrolling (even if to use the mouse wheel).

**Comment by rpkamp** [comment]
Noted
