### ISSUE TITLE
Support the "delete" button to remove bookmarks.

### ISSUE THREAD

**Issue by oleedd** [rpkamp/chrome-minimal-bookmarks-tree#103]
It is not convenient to open the right click menu and press "Delete" if need to delete many bookmarks. So it would be nice to add a listener for the "delete" button.

**Comment by rpkamp** [comment]
Must be solved as part of adding keyboard support: #42

**Comment by oleedd** [comment]
OK. But note that it is the most important and needed part.

**Comment by rpkamp** [comment]
none of it is important or needed.

**Comment by oleedd** [comment]
I mean in general. The reason is described above (speed).
So using the arrows is slower than using the mouse. But using the "delete" button is much faster than opening the menu. The sense is in speed. And people will always use the fastest ways.
