### ISSUE TITLE
Option to disable padding after folders

### ISSUE THREAD

**Issue by oleedd** [rpkamp/chrome-minimal-bookmarks-tree#105]

**Comment by rpkamp** [comment]
If only we supported themes :thinking: 

:stuck_out_tongue_closed_eyes:

**Comment by oleedd** [comment]
But what's the connection?

**Comment by rpkamp** [comment]
Well, how about a "compact" theme where everything is closer together than normal?

Themes is better than gazillions of options for how things should look.

**Comment by oleedd** [comment]
As I remember I have seen such an extension a long time ago and didn't like that look. But anyway, it is better to see what exactly you mean. You can use such bookmarks which I used in the video.

> Themes is better than gazillions of options for how things should look.

I don't agree. With options, users can customize as they want. Themes are good for "big" famous programs like WinRAR etc. where many modders create theme files with new icons, buttons. But not one or two persons. And users can find many nice themes in the net.

> "compact" theme

I don't think it is correct to call that a theme. It is more like a setting. Themes are just visual effects without changing distances, sizes.

**Comment by oleedd** [comment]
As I remember, I have seen such an extension a long time ago and didn't like that look. But anyway, it is better to see what exactly you mean. You can use such bookmarks which I used in the video.

> Themes is better than gazillions of options for how things should look.

I don't agree. With options, users can customize as they want. Themes are good for "big" famous programs like WinRAR etc. where many modders create theme files with new icons, buttons. But not one or two persons. And users can find many nice themes in the net.

> "compact" theme

I don't think it is correct to call that a theme. It is more like a setting. Themes are just visual effects without changing distances, sizes.

**Comment by rpkamp** [comment]
> I don't agree. 

Noted

> I don't think it is correct to call that a theme

Noted

**Comment by rpkamp** [comment]
See https://github.com/rpkamp/chrome-minimal-bookmarks-tree/issues/110
