### ISSUE TITLE
Mouse changes to scroll cursor on middle click

### ISSUE THREAD

**Issue by rpkamp** [rpkamp/chrome-minimal-bookmarks-tree#108]
As reported in Chrome Web Store

This does not happen for me on Linux, so it's probably a mac or windows thing.

**Comment by rpkamp** [comment]
I think this is a mac thing, but don't have a mac, so I can't check.

If anyone with a mac could test and fix this that would be awesome!

**Comment by r4dius** [comment]
Happens on windows too

**Comment by rpkamp** [comment]
Solved in version 5.2.2, thanks to @r4dius :slightly_smiling_face:
