### ISSUE TITLE
Add theming functionality

### ISSUE THREAD

**Issue by rpkamp** [rpkamp/chrome-minimal-bookmarks-tree#110]
Right now the popup is always black on white. It would be nice to give people some theme options so they can choose for example a dark theme that fits better with a dark chrome theme. Or a compact theme where things are all closer together, etc.

**Comment by oleedd** [comment]
Just see this extension: https://chrome.google.com/webstore/detail/minimal-bookmarks-tree/mohenkbngkbmdlkiemonbgdfgdjacaeb
It became very rich in settings. It has 7 colors settings, even with a gradient.
Besides, it generally doesn't display system folders.
About the number of users - 136k+. This should be an example.
To let you know.

**Comment by rpkamp** [comment]
Link seems incorrect, as that is _this_ extension.

At any rate, we discussed this. Multiple times. Let it go.

**Comment by oleedd** [comment]
Correct link: https://chrome.google.com/webstore/detail/bookmarks-menu/ffmdedmghpoipeldijkdlcckdpempkdi
Just see.

**Comment by oleedd** [comment]
Correct link: https://chrome.google.com/webstore/detail/bookmarks-menu/ffmdedmghpoipeldijkdlcckdpempkdi
Just see the colors settings.

**Comment by rpkamp** [comment]
This has been enabled now as of version 5.3.0
