### ISSUE TITLE
Right mouse click context menu opens too low when zoom > 100

### ISSUE THREAD

**Issue by rpkamp** [rpkamp/chrome-minimal-bookmarks-tree#114]
The current way zoom is implemented is annoying, because we'd need to take into account everywhere.

It's probably better to define the entire CSS in `rem`s and then just change the base font size of the HTML.

**Comment by oleedd** [comment]
Does it mean that we can't see some bottom bookmarks and the scrolling bar goes under the pop-up?
I described this problem in https://github.com/rpkamp/chrome-minimal-bookmarks-tree/issues/89.

**Comment by rpkamp** [comment]
No, it means the popup is too low. Instead of just below the mouse it is like 30px below the mouse.

**Comment by rpkamp** [comment]
To reproduce:

1. Set zoom to 200 in settings
2. Open extension 
3. Right click first folder / bookmark
4. Open a bookmark lower down in the extension

Note the difference between 3 and 4, the popup is too low with 4.

**Comment by oleedd** [comment]
Yes, I see this. But the title is very confusing - better to use "the right click menu" instead of "popup".

**Comment by rpkamp** [comment]
Fair enough. I've changed the title.

**Comment by oleedd** [comment]
Haha))) Have you seen how dragula works at zoom? Can you fix this? I haven't used it. I can fix the rest.

**Comment by oleedd** [comment]
Haha))) Have you seen how dragula works at zoom? It is related to this issue (the distance increases lower). Can you fix this? I haven't used it. I can fix the rest.

**Comment by oleedd** [comment]
Haha))) Have you seen how dragula works at zoom? It is related to this issue (the distance increases when moving). Can you fix this? I haven't used it. I can fix the rest.

**Comment by rpkamp** [comment]
More problems with zoom 😕
I think we should not use zoom. It's broken.

**Comment by oleedd** [comment]
Need to fix dragula - I almost fixed the rest.

**Comment by rpkamp** [comment]
It's near impossible to fix dragula, as it all calculated in javascript and I have no idea how to alter that.

I've fixed this by completely removing the zoom option. See https://github.com/rpkamp/chrome-minimal-bookmarks-tree/pull/124

**Comment by oleedd** [comment]
> It's near impossible to fix dragula

You are not right. I can do this. But need to understand how coordinates are changed at zoom. I will still complete this interesting task to grow as I have worked with coordinates before.

**Comment by rpkamp** [comment]
You can do it if you want to, but I will _not_ use the fix in Minimal Bookmarks Tree. Like I said, zoom is broken and I don't want to maintain it anymore.

_If_ you still want to fix it for yourself: when zoom is enabled, all distances are multiplied by (zoom / 100), so a distance of 2px with zoom 200 becomes 2 x (200 / 100) = 4px, a distance of 10 becomes 10px * (200 / 100) = 20px, etc.

It is not possible to fix without changing dragula itself to take zoom into account, and I'm definitely not maintaining a modified copy of dragula.

This is why zoom is broken. You have to modify _all_ calculations with coordinates to also use zoom. It's horrible.

By removing `zoom` support and using `rem` everything just works without having to change any coordinate calculations. It's much easier, and will work for any future changes as well.

**Comment by oleedd** [comment]
> BTW, "near impossible" mean "almost impossible" - I knew it was possible, just not in a nice way without changing dragula itself.

I know. But it requires to change dragula because it is need to use the zoom value in the coordinate calculations. It is not very hard but still hard. BTW "near impossible" is much harder than "very hard".

Moreover, I have own much shorter (but not worse - minimalism) project like dragula. So I try to fix my project because the problems are the same. Then it will be easy to fix dragula.

**Comment by oleedd** [comment]
Fixed. Created a formula.
It was very tangled because css properties, such as `style.top`/ `style.left` and `getBoundingClientRect()`, don't see any zoom. But coordinate properties. such as `clientX`/`clientY`, `pageX`/`pageY` and `pageYOffset`, see zoom. But need to combine all this. So it was "near possible".
BTW, it is very easy to fix #114 by using `pageX`/`pageY`.
