### ISSUE TITLE
Fonts with digits don't work

### ISSUE THREAD

**Issue by oleedd** [rpkamp/chrome-minimal-bookmarks-tree#120]
Moreover, fonts with digits are displayed by the current font in the <select> element - so not possible to even see how they actually look.

**Comment by oleedd** [comment]
As I see, `style.fontFamily` is applied to them.

**Comment by oleedd** [comment]
Because, as I see, `style.fontFamily` is not applied to them.

**Comment by rpkamp** [comment]
Which font did you try? I've got `C059`, `P052` and `Z003` on my machine, and all of them work fine with this extension.

**Comment by oleedd** [comment]
It should be with a space before digits like "Font 123".

**Comment by rpkamp** [comment]
I have no such font on my machine. Any suggestion of a free font I could use to and reproduce this?

**Comment by oleedd** [comment]
Bauhaus 93

**Comment by rpkamp** [comment]
Indeed, that doesn't work :thinking: 
I'll look into it!

**Comment by rpkamp** [comment]
Fixed in https://github.com/rpkamp/chrome-minimal-bookmarks-tree/pull/123
