### ISSUE TITLE
Building doesn't work on Windows after v4.9.1

### ISSUE THREAD

**Issue by oleedd** [rpkamp/chrome-minimal-bookmarks-tree#121]
The problem is after `make build-dev`:
```
node_modules/.bin/encore dev
"node_modules" is not recognized as an internal or external command, operable program or batch file.
make: *** [Makefile:15: build-dev] Error 1
```

**Comment by rpkamp** [comment]
Did must run `npm install` first, as stated in the README

**Comment by oleedd** [comment]
Of course I have run it.

**Comment by oleedd** [comment]
Of course I have run it because, as you see above, I already have the "node_modules" folder.

**Comment by oleedd** [comment]
See this: `https://github.com/JeffreyWay/laravel-mix/issues/151`

**Comment by rpkamp** [comment]
No idea. I've left Windows a long long time ago 😁

**Comment by oleedd** [comment]
But you can use a virtual machine.
I want to fix zoom but can't build. It is so sad. As a temporary solution, you give the non-compressed built version in zip.

**Comment by oleedd** [comment]
But you can use a virtual machine.
I want to fix zoom but can't build. It is so sad. As a temporary solution, you can give the non-compressed built version in zip.

**Comment by oleedd** [comment]
Or you can give v4.9.1 with grunt. Can you?

**Comment by rpkamp** [comment]
> But you can use a virtual machine.

Indeed, so could you :slightly_smiling_face: 

Are you running in the linux subsystem on windows, or in windows itself?

If you're running in windows itself, have you tried `node_modules\.bin\encore dev`? Windows uses `\` for directories, whereas linux uses `/`.

**Comment by rpkamp** [comment]
> Or you can give v4.9.1 with grunt. Can you?

Nope. 4.9.1 got rid of grunt because running SCSS with grunt/webpack sucks, so I'm not re-introducing it, that wouldn't make sense.

**Comment by oleedd** [comment]
There is no common with the "question" label. More like a bug for Windows.
`node_modules\.bin\encore dev` had worked :)
Seems that need to update README.
Is the `make` command (particularly installing MinGW with this command) not already need?

**Comment by rpkamp** [comment]
`make` is handy on Linux and MacOS, but it seems it doesn't work on windows. There are some hacks to get it to work, but would make the `make` file very complicated, so I won't do that.

I'll add additional instructions for Windows to the README.

**Comment by oleedd** [comment]
`make` works if to install `MinGW` and find `mingw32-make.exe`, rename it as "make" and put it in the directory.

**Comment by oleedd** [comment]
So it is much easier now if need to install only `npm`.

**Comment by oleedd** [comment]
`make` works if to install MinGW and find `mingw32-make.exe`, rename it as "make" and put it in the directory.
So it is much easier now if need to install only `npm`.

**Comment by rpkamp** [comment]
Glad you got it working :+1:
