### ISSUE TITLE
Add settings how system folders must be rendered

### ISSUE THREAD

**Issue by rpkamp** [rpkamp/chrome-minimal-bookmarks-tree#125]
**Is your feature request related to a problem? Please describe.**
Some people don't want to render some of the folders that are built in in the browser, like the Bookmarks menu in chrome.

**Describe the solution you'd like**
There should be settings in the settings panel for each folder how it should be rendered:

- Render folder itself, plus it's contents
- Render only folder contents
- Do not render contents

For backwards compatibility, folder 1 (the "bookmarks bar" in chrome) should default to "render folder itself, plus contents", and folder 2 (the "other bookmarks" in chrome) should default to "render only folder contents".

In addition, when the extension is installed in chrome, we should check if all of the user's system folders contain bookmarks. If there is just one folder with bookmarks we should mark that as "Render only folder contents" and ignore all other folders.

**Describe alternatives you've considered**
- Hide all system folders - which is not as customizable as the solution defined above
- Let the user select a root folder by themselves, which is not as flexible as the solution defined above

**Comment by oleedd** [comment]
Any progress?

**Comment by oleedd** [comment]
I think it should detect - if there are bookmarks only in one system folder, it is generally useless to display it. What do you think?

**Comment by oleedd** [comment]
I think it should check - if there are bookmarks only in one system folder, it is generally useless to display it. What do you think?

**Comment by rpkamp** [comment]
Yes, that makes sense.

**Comment by oleedd** [comment]
I mean that one option (hide a single system folder) is enough. Or even without this option - because no sense in displaying a single system folder.
I don't see any sense in the "Do not render contents" setting. It will not be in use.

**Comment by rpkamp** [comment]
We've had this conversation before, several times.

It _is_ useful, for browsers that have a "Trash" folder, like Vivaldi us.

**Comment by oleedd** [comment]
As a variant - to check the browser type at the installing event and add the "hide Trash" setting for Vivaldi, Opera. For Opera, it should be in `childrens[3]`.
+ the "hide a single system folder" feature.
Because seems that it is possible without rewriting the rendering algorithm.

**Comment by oleedd** [comment]
As a variant - to check the browser type at the installing event and add the "hide Trash" setting for Vivaldi, Opera. For Opera, it should be in `childrens[3]`.
\+ the "hide a single system folder" feature.
Because seems that it is possible without rewriting the rendering algorithm.

**Comment by rpkamp** [comment]
I'm fine rewriting the rendering algorithm. Taking shortcuts always has a price later on.
It's better to fix something by fixing the cause, then to fight the symptoms. The latter will resolve in a horrible system where thousands of things are going on that no-one can understand anymore.

**Comment by oleedd** [comment]
Any progress?

**Comment by oleedd** [comment]
Any progress?

**Comment by rpkamp** [comment]
Since nobody else asked for this and I really don't feel like doing it I'm closing this issue.
