### ISSUE TITLE
Ugly changes after removing zoom

### ISSUE THREAD

**Issue by oleedd** [rpkamp/chrome-minimal-bookmarks-tree#133]
Too big ugly scrolling button:
![image](https://user-images.githubusercontent.com/36125949/61243101-e6ec1f80-a74f-11e9-8d02-bc5c4febcc3c.png) - now
![image](https://user-images.githubusercontent.com/36125949/61243150-0420ee00-a750-11e9-85dd-ff99848d34d2.png) - before
Increased padding after folders:
![image](https://user-images.githubusercontent.com/36125949/61243372-798cbe80-a750-11e9-8034-bf549e13d147.png) - now
![image](https://user-images.githubusercontent.com/36125949/61243420-932e0600-a750-11e9-9170-e9ea735ca260.png) - before

**Comment by oleedd** [comment]
If 1 rem - padding looks like before.

**Comment by oleedd** [comment]
Can you change to 1 rem and fix the scrolling button?

**Comment by rpkamp** [comment]
I'll look into it

**Comment by oleedd** [comment]
m

**Comment by oleedd** [comment]
Now you use .75 rem for the scroll button width. Just use 8px as before and it is solved.

**Comment by oleedd** [comment]
Now you use .75rem for the scroll button width. Just use 8px as before and it is solved.

**Comment by rpkamp** [comment]
Done. I went for 1.2rem though instead of 1rem; that way the contents of the folder align with the name of the folder they're in, which looks nice.

**Comment by oleedd** [comment]
Why did you remove the right click menu design? It was nice.
![image](https://user-images.githubusercontent.com/36125949/61580547-16b67100-ab1c-11e9-9ca4-a5be38047e3b.png) - before
![image](https://user-images.githubusercontent.com/36125949/61580555-377ec680-ab1c-11e9-9637-1a81fcd4fbb5.png) - now

**Comment by oleedd** [comment]
Why did you remove the right click menu design? It was nice.
![image](https://user-images.githubusercontent.com/36125949/61580547-16b67100-ab1c-11e9-9ca4-a5be38047e3b.png) - before
![image](https://user-images.githubusercontent.com/36125949/61580555-377ec680-ab1c-11e9-9637-1a81fcd4fbb5.png) - now

Why is the edit panel defaulted?
![image](https://user-images.githubusercontent.com/36125949/61580780-2c2c9a80-ab1e-11e9-8972-2984d33d25a6.png) - before
![image](https://user-images.githubusercontent.com/36125949/61580800-59794880-ab1e-11e9-84a7-f563f10671a1.png) - now (too big height)

**Comment by rpkamp** [comment]
It is now more in line with how chrome itself displays things, providing a more consistent experience.

The reason the edit windows are so big now is because I felt they were cluttering the screen before. This way you only see the input fields without being distracted by all your other bookmarks / bookmark folders, which have nothing to do with the task at hand.

**Comment by oleedd** [comment]
I think it is worth to return the yellow color (`:hover`).
But the buttons "Save" and "Chancel" were volumetric before.

**Comment by oleedd** [comment]
I think it is worth to return the yellow color (`:hover`).
But the "Save" and "Cancel" buttons were volumetric before.

**Comment by oleedd** [comment]
What about making buttons volumetric as before? 3D is better than 2D.
What do you think about returning the yellow color (`:hover`)? It was very nice.

**Comment by rpkamp** [comment]
As said before, I'm going for the look of chrome itself, and those buttons are flat, so the buttons of this extension are now flat as well.

The yellow was nice but doesn't fit with the new theme and chrome doesn't use yellow anywhere either, so I'm not bringing that back.

**Comment by oleedd** [comment]
So if you don't use many colors anymore - you can implement the option for background/font colors.

**Comment by oleedd** [comment]
So if you don't use many colors anymore - you can implement the option for the background/font colors.

**Comment by rpkamp** [comment]
Nope. As discussed, I'm going with themes. That decision has been made.
