### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by rpkamp** [rpkamp/chrome-minimal-bookmarks-tree#139]
**Is your feature request related to a problem? Please describe.**
When Chrome is in dark mode, both the background as well as the text of the bookmarks panel are black.

**Describe the solution you'd like**
Text should be readable (white?) when in dark mode. Build themes functionality to achieve this; when dark mode is selected, use dark theme automatically on installation.

**Describe alternatives you've considered**
None

**Comment by xPaw** [comment]
There's the hidden theme option which has a dark style and it mostly works.

The only things I noticed broken with it is the folder text color, and hover state that needs tweaking.

**Comment by rpkamp** [comment]
Does the hidden theme work better for you than the native dark mode from chrome?

**Comment by xPaw** [comment]
I actually have the dark mode enabled in Windows (so in Chrome as a result too), and the extension was still white.
