### ISSUE TITLE
Remove/hide bookmarks bar

### ISSUE THREAD

**Issue by friederbluemle** [rpkamp/chrome-minimal-bookmarks-tree#155]
This might be outside the scope of this extension, but is there a way to remove/hide the Google Chrome bookmarks bar when a new tab is opened? It is not really necessary anymore with this extension.

It is incredibly annoying to have a bunch of personal bookmarks pop up every time you open a new tab when doing a screenshare at work.

**Comment by rpkamp** [comment]
This is built into chrome itself, just hit ctrl + shift + b (or command + shift + b on mac I guess?)

**Comment by rpkamp** [comment]
There are several "new tab" extensions that override the blank page. most of them hide the bookmarks bar too.

https://chrome.google.com/webstore/search/new%20tab?_category=extensions

**Comment by friederbluemle** [comment]
Thanks for the reply!

Yeah, Ctrl+Shift+B toggles "Show bookmarks bar" in the Settings. Unfortunately it only makes the bookmarks bar either always visible, or hides it on tabs _once a url has been loaded_. Like you said, it has no effect on the new tab page.
I'll try some of the extensions you suggested.

**Comment by friederbluemle** [comment]
For the future reader:

I installed the [**Empty New Tab Page**](https://chrome.google.com/webstore/detail/empty-new-tab-page/dpjamkmjmigaoobjbekmfgabipmfilij) extension which shows a blank page without the bookmarks bar.


Thanks again!
