### ISSUE TITLE
changing background/foreground colors

### ISSUE THREAD

**Issue by gothmog123** [rpkamp/chrome-minimal-bookmarks-tree#34]
Would it be possible to implement this? Thanks

**Comment by oleedd** [comment]
Here may be used `<input type="color">` to change background and font colors. Just need to track changes of its value. It works amazingly.
Info: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color

**Comment by rpkamp** [comment]
I implemented this with `<input type="color">` and that works just fine. The problem is there are much more colors involved than just a foreground color and a background color.
So instead of letting the user pick the colors I will supply built in themes instead, starting with light (the current theme) and dark (a new theme with a black background) and maybe some others as well.

Did you have a specific color scheme in mind for this @gothmog123 ?

**Comment by oleedd** [comment]
> The problem is there are much more colors involved than just a foreground color and a background color.

What do you mean? There are only background and font colors. What else? People may want the green font or the rose background. Or both. It can't be solved with themes. It is impossible because about 15 millions of colors.

**Comment by rpkamp** [comment]
Boy, you just love confrontation, don't you? 

Well, the popup menu and the buttons in the confirmation window have colors as well. It's impossible to know which colors they need based on two colors.

**Comment by oleedd** [comment]
No, I don't. Confrontation is only worth it if there is a sense.
Changing colors for menus is generally unnecessary. Besides people see them rarely. Just leave them as they are.

**Comment by rpkamp** [comment]
> Changing colors for menus is generally unnecessary. Besides people see them rarely. Just leave them as they are.

That's _your_ opinion. I don't like an experience of the extension where you can change some part of it, but not all, that may result in an ugly screen.

Themes give the ability for a much more consistent look and feel across the board.

Also, when giving people the power to change these kinds of things you'll inevitably run into those who set foreground and background to the same color and then wonder why they can't read anything anymore. I really don't want to deal with that.

So, themes it is :smile: 

(if you want customizable colors, feel free to fork this repository and change it in your own fork)

End of.

**Comment by oleedd** [comment]
> Also, when giving people the power to change these kinds of things you'll inevitably run into those who set foreground and background to the same color and then wonder why they can't read anything anymore. I really don't want to deal with that.

If somebody will do this - just for fun - and will understand the reason for sure. No need to worry about such cases. Moreover, the chosen color is displayed in `<input type="color">`. I have seen several bookmark extensions which have such color options and no problems there.

With themes, you can't do all what people want.
But you can add both themes and color options. Such color settings were implemented in some new version of Opera and it is very nice there.
But themes are not only colors but also some gradient etc.

**Comment by rpkamp** [comment]
Issue continues here: https://github.com/rpkamp/chrome-minimal-bookmarks-tree/issues/110
