### ISSUE TITLE
Small new Icons.

### ISSUE THREAD

**Issue by Aleck85** [rpkamp/chrome-minimal-bookmarks-tree#5]
The new icons is too small. Please make them larger.

Old 
![_](https://cloud.githubusercontent.com/assets/5072865/6847253/2388adde-d3d6-11e4-80f7-947ecec9ca5d.JPG)

New
![_ _ 1](https://cloud.githubusercontent.com/assets/5072865/6847257/2b520588-d3d6-11e4-8f04-1db45b2257db.JPG)

**Comment by rpkamp** [comment]
Fixed in the latest version (v1.21)
