### ISSUE TITLE
Support fonts using css

### ISSUE THREAD

**Issue by oleedd** [rpkamp/chrome-minimal-bookmarks-tree#65]
New option like "bookmarks font name" using css. It is very easy to do. Just to add css to bookmark table.

**Comment by rpkamp** [comment]
Sounds fine in theory, but I'll probably get a lot of support questions from people who typed some font that is not installed on their computer and then complain to me that the feature isn't working properly, or they enter something like wingdings and then get confused by the output.

I don't feel like that's worth implementing it.

**Comment by oleedd** [comment]
I agree with you about the "a lot of support questions" problem. So need to make checking and if a font is not installed - to display a warning.

**Comment by oleedd** [comment]
I agree with you about the "a lot of support questions" problem. So need to make checking and if a font is not installed - to display a warning "font with such name is not installed in your system".

**Comment by rpkamp** [comment]
Problem is though that there is no reliable way to check that.
I'd be happy to know if you know of any, but until then this ticket will remain closed.

**Comment by oleedd** [comment]
Please inspect this way:
https://www.samclarke.com/javascript-is-font-available/
Also chrome font api may help:
https://developer.chrome.com/extensions/fontSettings

And the second way is soft warning with test alphabet block in settings:
"If you don't see font effect then the font with such name is not installed in your system".

And the third and the easiest way:
Option to add css and only people who know it will able to use it and they will understand the result anyway.

**Comment by rpkamp** [comment]
> Also chrome font api may help:
> developer.chrome.com/extensions/fontSettings

That might just work. I'll look into that.

**Comment by oleedd** [comment]
As I see it is only possible by checking the entire font list.

```javascript
chrome.fontSettings.getFontList(function(fonts) {
   for (var font of fonts) {
      if (font.displayName == "Times New Roman") var exist = true;
   }
   if (!exist) alert("error");
})
```
Also good news that the fontSettings permission is not shown in details of an extension. It is only in manifest.

**Comment by oleedd** [comment]
As I see it is only possible by checking the entire font list. I have checked this and it works.

```javascript
chrome.fontSettings.getFontList(function(fonts) {
   for (var font of fonts) {
      if (font.displayName == "Times New Roman") var exist = true;
   }
   if (!exist) alert("error");
})
```
Also good news that the fontSettings permission is not shown in details of an extension. It is only in manifest.

**Comment by rpkamp** [comment]
Yeah I was thinking to take the fonts and put them all in a dropdown so people can select one of their existing fonts. That would probably be easiest.

**Comment by oleedd** [comment]
Good. But in this case fonts should be used in their names as MS Word does.
![image](https://user-images.githubusercontent.com/36125949/51859999-31fcac80-2341-11e9-93be-575eec03f739.png)
It should be easy with css.

**Comment by rpkamp** [comment]
I'll look into it, although IIRC styling individual options of a dropdown doesn't really work.

**Comment by oleedd** [comment]
What dropdown do you mean?
If <select> element which you used for options - fonts works for <option> elements. I have checked this.
![image](https://user-images.githubusercontent.com/36125949/51866062-9a06bf00-2350-11e9-88b3-9e534a376dfc.png)

**Comment by oleedd** [comment]
What dropdown do you mean?
If element which you used for options - fonts works for elements. I have checked this.
![image](https://user-images.githubusercontent.com/36125949/51866092-ab4fcb80-2350-11e9-9f13-f7ed977c145b.png)

**Comment by oleedd** [comment]
What dropdown do you mean?
If `<select>` element which you used for options - fonts works for `<option>` elements. I have checked this.
![image](https://user-images.githubusercontent.com/36125949/51866092-ab4fcb80-2350-11e9-9f13-f7ed977c145b.png)

**Comment by oleedd** [comment]
What dropdown do you mean?
If the \<select\> element which you used in the settings - fonts works for \<option\> elements. I have checked this.
![image](https://user-images.githubusercontent.com/36125949/51866092-ab4fcb80-2350-11e9-9f13-f7ed977c145b.png)

**Comment by oleedd** [comment]
What dropdown do you mean?
If the \<select\> element which you used in the settings - fonts work for \<option\> elements. I have checked this.
![image](https://user-images.githubusercontent.com/36125949/51866092-ab4fcb80-2350-11e9-9f13-f7ed977c145b.png)

**Comment by oleedd** [comment]
For example if \<select id="fontList"\> - the next code creates the whole list of system fonts using fonts in displaying their names .
```javascript
fontList.onchange = function() {
	this.style['font-family'] = this.value;
}
chrome.fontSettings.getFontList(function(fonts) {
	for (var font of fonts) {
   		var option = document.createElement("option");
   		option.textContent = font.displayName;
   		option.style['font-family'] = font.displayName;
		fontList.appendChild(option);
	}
})
```

**Comment by oleedd** [comment]
Why didn't you use this if it displays selected font name using that font for \<select\> element?
```
fontList.onchange = function() {
	this.style.fontFamily = this.value;
}
```

**Comment by rpkamp** [comment]
I did:

```
fonts.forEach((font) => {
  const option = window.document.createElement('option');
  option.textContent = font.displayName;
  option.style.fontFamily = font.displayName;
  option.textContent = font.displayName;
  fontList.appendChild(option);
});
```

**Comment by oleedd** [comment]
I mean not that.
Real result:
![image](https://user-images.githubusercontent.com/36125949/53298990-d9380b00-383d-11e9-889f-6ea595120c96.png)
Expected result:
![image](https://user-images.githubusercontent.com/36125949/53299020-20be9700-383e-11e9-98c1-b9776ac1b29c.png)

**Comment by rpkamp** [comment]
Weird, it works for me:

![screenshot from 2019-02-24 13-19-25](https://user-images.githubusercontent.com/1059790/53299134-f3bab600-3836-11e9-84f5-eccbda973995.png)

**Comment by rpkamp** [comment]
Oh wait, you mean once you've selected it. Yes that's not working at the moment.
I'll add that in the next version :+1:

**Comment by oleedd** [comment]
Yes. I mean only the \<select\> element. \<option\> elements work.
My code (above) works for that but for some reason the size of the rectangle with \<select\> is changed for each font for some reason. So maybe need to set size limits.

**Comment by oleedd** [comment]
Yes. I mean only the \<select\> element. \<option\> elements work.
My code (above) works for that but the size of the rectangle with \<select\> is changed for each font for some reason. So maybe need to set size limits.

**Comment by rpkamp** [comment]
Fixed in https://github.com/rpkamp/chrome-minimal-bookmarks-tree/pull/84, but not rolling out to Chome Webstore yet.

**Comment by oleedd** [comment]
It still doesn't work in 4.8.1.

**Comment by oleedd** [comment]
It already works in 4.8.5.
A little detail. Is it normal that the weight of the font select is different for different fonts? Sometimes it does not fit into the line.
![image](https://user-images.githubusercontent.com/36125949/54306549-4257a680-45d2-11e9-8a83-d15fff1093b4.png)
![image](https://user-images.githubusercontent.com/36125949/54306586-56030d00-45d2-11e9-8f91-daae5785a295.png)

**Comment by oleedd** [comment]
Also found a little bug to let you know. `Default` property is not static. It gets the last font value.
![image](https://user-images.githubusercontent.com/36125949/54308018-c2334000-45d5-11e9-97d3-231a86e5d8fc.png)
or
![image](https://user-images.githubusercontent.com/36125949/54308284-63ba9180-45d6-11e9-8614-94862c957da9.png)
