### ISSUE TITLE
[Bug] Losing all saved settings

### ISSUE THREAD

**Issue by oleedd** [rpkamp/chrome-minimal-bookmarks-tree#66]
If there is no free place on drive C even for less than a minute, then all previously saved settings are reset and need to re-configure all again. Please fix.

**Comment by rpkamp** [comment]
A computer can't store anything if there is no free space. Nothing can be done about that. Just make sure your C drive is never full.

**Comment by rpkamp** [comment]
Also, this is a chrome issue, if I wanted to change something about this I couldn't, since extensions don't have that kind of power.

**Comment by oleedd** [comment]
You didn't correctly understand the issue.
Settings are stored when there was much free place. And all was saved and worked. But if there is no free place for very short time, then settings are lost (they were not changed since there was free place). And it is always so. Very sad.
The thing is that other extensions (for example AdGuard) are not losing its settings in such case. Only your extension and some proxy extension.
So please try to fix.
Btw is there used storage.sync or storage.local api?

**Comment by rpkamp** [comment]
`storage.local`

**Comment by rpkamp** [comment]
Feel free to create a PR if you think you can fix this, but I won't pursue it in my free time.

**Comment by oleedd** [comment]
One extension, I use, doesn't have this problem and uses storage.sync api. So I am almost sure that it is caused by not perfect storage.local api. So this may be fixed by just replacing local by sync in the code.
