### ISSUE TITLE
[Bug] Incorrect position displaying on empty tabs

### ISSUE THREAD

**Issue by oleedd** [rpkamp/chrome-minimal-bookmarks-tree#67]
Steps to reproduce:
1. Open any site and press the extension icon.
2. Open new tab (empty) and press the extension icon.

Position on empty tabs is always 2 bookmarks higher. And if to load any site, it becames correct. And if to simply switch between empty and non-empty tabs - position is different.
To easy reproduse it is better to scrool to the bottom with the last bookmark.

**Comment by oleedd** [comment]
Max-height value of #wrapper is always 474px for empty tabs (in settings preferred height is 600).
It is related to https://github.com/rpkamp/chrome-minimal-bookmarks-tree/issues/68.

**Comment by rpkamp** [comment]
Solution to https://github.com/rpkamp/chrome-minimal-bookmarks-tree/issues/68 seems to solved this as well. Could you verify?

**Comment by oleedd** [comment]
Yes. The issue is gone. Thanks.
