### ISSUE TITLE
[Bug] Pop-up height limit

### ISSUE THREAD

**Issue by oleedd** [rpkamp/chrome-minimal-bookmarks-tree#68]
Please look at this extension. Why does it have on 2 centimeters bigger pop-up height than "chrome 600 limited" height of chrome-minimal-bookmarks-tree?
https://chrome.google.com/webstore/detail/adguard-adblocker-beta/gfggjaccafhcbfogfkogggoepomehbjl

**Comment by rpkamp** [comment]
I don't know what you're seeing on your end, but here the AdGuard popup is 598px tall.

**Comment by oleedd** [comment]
But AdGuard pop-up is higher for some reason.
![2019-01-22_185131](https://user-images.githubusercontent.com/36125949/51552247-d9c53680-1e78-11e9-8771-6dc92eee1a88.jpg)

**Comment by oleedd** [comment]
If to change this max-height value to 600px then pop-up height is so big as in AdGuard. In preferences it is 600px but in reality it is always 562px. There seems to be a bug in css.
![image](https://user-images.githubusercontent.com/36125949/51570620-24aa7280-1ea8-11e9-9de1-ecf5154ebd10.png)

**Comment by rpkamp** [comment]
Sounds like you have a grasp on this. Feel free to create a PR :slightly_smiling_face:

**Comment by oleedd** [comment]
I have never made a PR yet.
You can fix this for 5 minutes.
But for me it is need at least several hours to analyze its big code with many modules to not break something.
So please fix this yourself. You know how your extension works. This problem is very annoying because   height is somethimes small, somethimes medium but it is never 600px (((
But I can help with any problem if it will be.

**Comment by oleedd** [comment]
I have made a quick fix for this problem. But I want to check it firstly. If to load the extension from scr folder to Chrome - it doesn't work.
Can your give working uncompressed version of the extension?

**Comment by rpkamp** [comment]
This repository _is_ an uncompressed working version of the extension :slightly_smiling_face: 

See the [README](https://github.com/rpkamp/chrome-minimal-bookmarks-tree/blob/master/README.md) for instructions on how to get started.

**Comment by oleedd** [comment]
I don't want to play with modules, install programs and learn how to make it working. I don't understand the instruction.
Please give here the working uncompressed extension in zip archive and I will give the fix after checking.

**Comment by oleedd** [comment]
I don't want to play with modules, install programs and learn how to make it working. I don't understand the instruction.
Please give here the working uncompressed extension in zip archive (which is ready for installing in Chrome) and I will give the fix after checking.

**Comment by rpkamp** [comment]
That's not really workable, as I'd have to reverse engineer what you did, which would take a lot of time.

I'll look into this later.

**Comment by oleedd** [comment]
I just need uncompressed ready version. I don't understand the sense of the problem you describe but just need to assemble it as you did before, but without compressing.
The fix is only in function setElementDimensions(). But it is problematic to find this function in the version from chrome store.

**Comment by rpkamp** [comment]
If you could post your correct `setElementDimensions` here I'd be happy to put it in.

**Comment by oleedd** [comment]
It should work. But I am not sure for 100 % without checking.
```javascript
function setElementDimensions(tab, selector, preferredWidth, preferredHeight, zoom) {
  var width;
  var height;
  chrome.windows.getCurrent(function(e) {
    if (e.state == "maximized" || e.state == "fullscreen") {
      height = preferredHeight;
      width = preferredWidth;
    } else {
    height = Math.round(preferredWidth * e.width / screen.availHeight);
    width = Math.round(preferredHeight * e.height / screen.availHeight);
    }
  })

  const elem = document.querySelector(selector);
  if (elem === null) {
    return;
  }

  elem.style.width = `${width}px`;
  elem.style.minWidth = `${width}px`;
  elem.style.maxWidth = `${width}px`;
  elem.style.maxHeight = `${height}px`;
}
```
So here is used chrome window api to know window format. If its size is reduced -  the proportion is used to make the percentage ratio of pop-up area and window area the same.

**Comment by oleedd** [comment]
It should work. But I am not sure for 100 % without checking.
```javascript
function setElementDimensions(tab, selector, preferredWidth, preferredHeight, zoom) {
  var height, width;
  chrome.windows.getCurrent(function(e) {
    if (e.state == "maximized" || e.state == "fullscreen") {
      height = preferredHeight;
      width = preferredWidth;
    } else {
    height = Math.round(preferredWidth * e.width / screen.availHeight);
    width = Math.round(preferredHeight * e.height / screen.availHeight);
    }
  })

  const elem = document.querySelector(selector);
  if (elem === null) {
    return;
  }

  elem.style.width = `${width}px`;
  elem.style.minWidth = `${width}px`;
  elem.style.maxWidth = `${width}px`;
  elem.style.maxHeight = `${height}px`;
}
```
So here is used chrome window api to know window format. If its size is reduced -  the proportion is used to make the percentage ratio of pop-up area and window area the same.

**Comment by rpkamp** [comment]
Okay I think I found the issue. MBT was trying to be nice and leave at least 100px free at the bottom of the screen, and it would lower the `max-height` for that to a value lower than the user indicated.

I've created a new version that no longer tries to be nice and just sets `max-height` to whatever the user set it to, and chrome can then figure out what the actual height should be.

I've just published the new version, it should arrive at your device within the next hour. Could you please verify that this works better?

**Comment by rpkamp** [comment]
Cool. I'll consider this closed then :+1:

**Comment by oleedd** [comment]
Please explain what is "Animation speed"? I tried many times to see it but I don't understand where should it work.

**Comment by rpkamp** [comment]
It changes the speed with which folders expand/collapse.
