### ISSUE TITLE
Doesnt work in vivaldi. 

### ISSUE THREAD

**Issue by Aleck85** [rpkamp/chrome-minimal-bookmarks-tree#7]

**Comment by rpkamp** [comment]
Why did you close this ticket? Does it work after all?

**Comment by Aleck85** [comment]
Oops, I dont want to close it. No, doesent work.

**Comment by rpkamp** [comment]
Fixed it so it works in Vivaldi too. Publishing to the chrome web store now and should arrive within the next hour (default chrome web store behaviour, not something I have control over).

Please let me know if it works for you too.

**Comment by rpkamp** [comment]
Since I haven't heard anything from you I will just assume it works and close this ticket.
