### ISSUE TITLE
[Bug] Zoom level

### ISSUE THREAD

**Issue by oleedd** [rpkamp/chrome-minimal-bookmarks-tree#89]
If `Zoom level` is more than 100 - the scrolling button doesn't stop at the bottom and goes under the screen + additional area after the scrolling line appears.
![image](https://user-images.githubusercontent.com/36125949/54323358-96c64a80-4601-11e9-9ee6-6b9a1cad9826.png)

**Comment by rpkamp** [comment]
PR created: https://github.com/rpkamp/chrome-minimal-bookmarks-tree/pull/97

**Comment by rpkamp** [comment]
Released as part of v4.9.0

**Comment by oleedd** [comment]
Why does it resize height/width?
How can users set preferred height/width if it is simply ignored with zoom?
It looks like a bug now.
The golden rule of programming: never ignore user settings.

**Comment by rpkamp** [comment]
Well I was in doubt about that one. The thing is, if you install this out of the box and _only_ change the zoom level, you get a very small window and can't read anything, so you will also have to increase the width and height as well.

I guess though you're right that that would be easier to understand. I agree and no longer multiply the height and width by the zoom level. That would make that method considerably easier as well, riddled as it is now with `Math.min()`.

See https://github.com/rpkamp/chrome-minimal-bookmarks-tree/issues/106

**Comment by oleedd** [comment]
Also there wasn't resizing before.
> The thing is, if you install this out of the box and only change the zoom level, you get a very small window and can't read anything, so you will also have to increase the width and height as well.

Yes, I agree. But there is a big problem in customization. A user approximately remember how the pop-up looks at different height/width with 100% zoom. But at any another zoom, previous feelings will not work. So there is total confusion and need to guess. And the only way to set some exact-pixel size is to calculate (according to zoom).

It would be more normal if not Chrome size limits :( So Chrome will simply ignore some resizing.
