### ISSUE TITLE
Bug in font dropdown

### ISSUE THREAD

**Issue by rpkamp** [rpkamp/chrome-minimal-bookmarks-tree#90]
Reported by @oleed:

Also found a little bug to let you know. `Default` property is not static. It gets the last font value.
![image](https://user-images.githubusercontent.com/36125949/54308018-c2334000-45d5-11e9-97d3-231a86e5d8fc.png)
or
![image](https://user-images.githubusercontent.com/36125949/54308284-63ba9180-45d6-11e9-8614-94862c957da9.png)

**Comment by oleedd** [comment]
That is not me - not  <del>oleed</del> but @oleedd.

**Comment by oleedd** [comment]
not <del>@oleed</del> but @oleedd

**Comment by rpkamp** [comment]
Pull request opened: https://github.com/rpkamp/chrome-minimal-bookmarks-tree/pull/95

**Comment by oleedd** [comment]
I don't think it is a good way to check all fonts. It is not optimal. The best way is to set the default font css to this `<option>` element when you create it.

**Comment by rpkamp** [comment]
The problem is that if I don't check for `__default__` then the extension will set the font-family for the `select` to the font `__default__`, which doesn't exist, but causes the browser to render some other font than the default (no idea which is selects).

I agree that setting a default would be better, but it's system dependent, so I can't know for all computers what their default font is, so I can't supply one.

>  It is not optimal.
Correct, but it's not like people use this several times a day, I'm sure they can wait an extra few milliseconds when they want to change the font :wink:

**Comment by oleedd** [comment]
Maybe you can use just this after `<select>` with all fonts is built:
`dropdowns[0].style.fontFamily = "revert"`
I think rewriting is better than many checks.
Also it is better to create the "Default" option not in a html file but using JS after `<select>` with all fonts is built. It makes no problems.

**Comment by rpkamp** [comment]
> dropdowns[0].style.fontFamily = "revert"

That just replaces the CSS, the checking against `__default__` would still be needed.

> Also it is better to create the "Default" option not in a html file but using JS after <select> with all fonts is built. It makes no problems.

It doesn't really matter. Since it must be there always I prefer it in the HTML as that makes it more clear that it will always be there. It's really not important though.

**Comment by oleedd** [comment]
OK. An iron working way:
`font.children[0].style.fontFamily = "revert"`

**Comment by oleedd** [comment]
OK. An iron working way:
`font.children[0].style.fontFamily = "revert"`
Or to use "fontList" here:
![image](https://user-images.githubusercontent.com/36125949/59975293-74a87500-95bf-11e9-9b32-e0a3b0d5dd6f.png)
I check and it works. So only one string fixes this issue without any additional checks.

**Comment by oleedd** [comment]
OK. An iron working way:
`font.children[0].style.fontFamily = "revert"`
Or to use "fontList" here:
![image](https://user-images.githubusercontent.com/36125949/59975293-74a87500-95bf-11e9-9b32-e0a3b0d5dd6f.png)
I have checked this and it works. So only one string fixes this issue without any additional checks.

**Comment by rpkamp** [comment]
No it does not. The issue is that it sets `font-family: __default__` on the `<select>` element. Your fix does not solve that.

It's fine as is. I don't care about an extremely minor performance thing in a settings form. I didn't actually notice any delay.

Don't fix something that isn't broken.

**Comment by rpkamp** [comment]
Ah, I get it now. It's just that I didn't understand because you solved in the javascript what I would have solved in the HTML.

I've solved it in the HTML now: https://github.com/rpkamp/chrome-minimal-bookmarks-tree/pull/100

Thanks :+1:

**Comment by oleedd** [comment]
Oh. I meant exactly that initially :+1:
> Don't fix something that isn't broken.

Not possible to fix something that isn't broken. It is only about improving.
