### ISSUE TITLE
Bookmarks without text show favicon in half height

### ISSUE THREAD

**Issue by rpkamp** [rpkamp/chrome-minimal-bookmarks-tree#91]
As reported in the Chrome Web Store.

Should probably use a single space for a bookmark without any text, quite hackish, but by far the easiest solution.

**Comment by oleedd** [comment]
Spaces will not be saved.

**Comment by oleedd** [comment]
Spaces will not be saved - only a single space (not more) between two symbols may be saved.

**Comment by rpkamp** [comment]
I'm not talking about saving a space, I'm talking about rendering a space when the bookmark name is empty.

**Comment by oleedd** [comment]
It also doesn't work if to add spaces to the `<span>` element.
About saving spaces - it turned out that they are saved but not displayed.

**Comment by rpkamp** [comment]
Released as part of v4.9.0
