### ISSUE TITLE
All folders without bookmarks should be hidden

### ISSUE THREAD

**Issue by oleedd** [rpkamp/chrome-minimal-bookmarks-tree#92]
Empty (system) folders, which have another empty folder, should be hidden too.

**Comment by rpkamp** [comment]
There already is a setting for this, "Hide empty folders". Is it not working for you?

**Comment by oleedd** [comment]
No. It works only for a generally empty folder. But it doesn't hide a folder without bookmarks but with a child empty folder. But only the child folder will be hidden.

**Comment by rpkamp** [comment]
Ah that makes sense. I'll look into it!

**Comment by rpkamp** [comment]
PR opened: https://github.com/rpkamp/chrome-minimal-bookmarks-tree/pull/94

**Comment by rpkamp** [comment]
Released as part of v4.9.0
